### ISSUE TITLE
Unable to load V2 secret or public key with base64

### ISSUE THREAD

**Issue by peterwallhead** [authenticvision/libpaseto#9]
Using an ESP32. Coding in Arduino.

I'm attempting to use ```paseto_v2_public_load_secret_key_base64``` and ```paseto_v2_public_load_public_key_base64``` functions but I'm unable to load the the keys. 

I've attempted many different base64 encoding methods, including the base encoded strings generated by openssl, but not had any luck so far.

I note that https://github.com/authenticvision/libpaseto/blob/master/examples/example.c is the ```paseto_v2_local_load_key_base64``` function and this works as expected.

I also note that you've written some tests for the ```paseto_v2_public_load_secret_key_hex``` function, and using this function with the same hex encoded strings works as expected.

Would you be able to add an example using the ```paseto_v2_public_load_secret_key_base64``` and ```paseto_v2_public_load_public_key_base64``` functions please?

**Comment by minus7** [comment]
I've added an example to [generate keys](https://github.com/authenticvision/libpaseto/blob/c4472926cca253b381f040e725282a9558c8efa4/examples/gen-keys.c) and one [using the v2.public API](https://github.com/authenticvision/libpaseto/blob/c4472926cca253b381f040e725282a9558c8efa4/examples/example_v2_public.c). The `*_base64` functions expect base64-encoded text using the URL variant (i.e. `-` and `_` instead of `+` and `/`) and omit the `=` padding. I hope this helps.

**Comment by peterwallhead** [comment]
Brilliant, thank you for your quick reply and work!

Looks like base64-encoding the keys using the URL variant was the missing step here.

I'll replicate your examples into my code next week and update you.

If I get time I'll have a go at adding in some more test cases for the V2.public API for you too.

**Comment by peterwallhead** [comment]
I was able to integrate your example code into my project quickly and seamlessly. Thank you again.
